name: docs

on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with :
          ref: "main"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: install dependencies
        run: |
          pip install .
          pip install -r docs/requirements.txt

      - name: build and push
        run: |
          mkdir ~/.ssh
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.DOC_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          
          git config --local user.email "takumi.ando826@gmail.com"
          git config --local user.name tand826
          git remote set-url origin git@github.com:tand826/wsiprocess.git

          cd docs
          sphinx-apidoc ../wsiprocess -o ./ -f --ext-autodoc
          make html
          cp -r _build/html/* ./

          git add ./
          git commit -m "generate documentation from github action"
          git push origin main
